name = "SaavnAPI"
main = "./src/app/api/[[...route]]/route.ts"
compatibility_date = "2024-09-28"
compatibility_flags = ["nodejs_compat"]

[env.production]
routes = [
  { pattern = "*.jiosaavndevs.workers.dev", zone_name = "workers.dev" }
]

[observability]
enabled = true

[build]
cwd = "."
command = "npm run build"
watch_paths = ["src/**/*.ts", "api/**/*.ts"]

[placement]
region = "aws:ap-south-1"
